#!/bin/bash
#Because I am a lazy bastard and refuse to type all those commands.

#First off the reviews.txt file.
mv reviewsGIVEN.txt reviewsGIVEN.bak && sort reviewsGIVEN.bak | uniq -u > reviewsGIVEN.txt


#Secondly, the scores.txt file

mv scoresGIVEN.txt scoresGIVEN.bak && sort scoresGIVEN.bak | uniq -u > scoresGIVEN.txt


#Thirdly, the rterms.txt file.
mv rtermsGIVEN.txt rtermsGIVEN.bak && sort rtermsGIVEN.bak | uniq -u > rtermsGIVEN.txt



#Finally (fourthly) the pterms.txt file.
mv ptermsGIVEN.txt ptermsGIVEN.bak && sort ptermsGIVEN.bak | uniq -u > ptermsGIVEN.txt



#Delete the .bak files! 
#Yes I realize I could use a blanket statement to delete them but I am 
#SIGNIFICANTLY more comfortable actually deleting them one by one
#"manually" like this!

rm reviewsGIVEN.bak

rm scoresGIVEN.bak

rm rtermsGIVEN.bak

rm ptermsGIVEN.bak

echo "... Everything is done, I hope! :)"
echo "File sorting should have been successful!"
