#!/bin/bash

chmod 755 thisIsTheSortCommandThatWorks
./thisIsTheSortCommandThatworks



rm scoresPreppedForDB.txt
rm reviewsPreppedForDB.txt
rm ptermsPreppedForDB.txt
rm rtermsPreppedForDB.txt

#echo "Removed all old prepared DB files just to be confident!"

python3 dbLoadChangeFileFormat.py scoresGIVEN.txt scoresPreppedForDBGIVEN.txt
#echo "Created file: scoresPreppedForDB.txt for db_load"

python3 dbLoadChangeFileFormat.py reviewsGIVEN.txt reviewsPreppedForDBGIVEN.txt
#echo "Created file: reviewsPreppedForDB.txt for db_load"

python3 dbLoadChangeFileFormat.py ptermsGIVEN.txt ptermsPreppedForDBGIVEN.txt
#echo "Created file: ptermsPreppedForDB.txt for db_load"

python3 dbLoadChangeFileFormat.py rtermsGIVEN.txt rtermsPreppedForDBGIVEN.txt
#echo "Created file: rtermsPreppedForDB.txt for db_load"



#Remove old database files before loading new ones.

rm rw.idx
rm pt.idx
rm rt.idx
rm sc.idx

#echo "attempting to put the database together...."
#echo "First let's try... putting into the db_lad the scores...."
cat reviewsPreppedForDBGIVEN.txt | db_load -c duplicates=1 -T -t hash rw.idx


cat ptermsPreppedForDBGIVEN.txt | db_load -c duplicates=1 -T -t btree pt.idx

cat rtermsPreppedForDBGIVEN.txt | db_load -c duplicates=1 -T -t btree rt.idx

cat scoresPreppedForDBGIVEN.txt | db_load -c duplicates=1 -T -t btree sc.idx

echo "If you saw no error messages here we prepped files and made indexes successfully"


